---
- name: Create group for service user
  group:
    name: "{{ user.group }}"
    state: present

- name: Create user for service
  user:
      name: "{{ user.name }}"
      group: "{{ user.group }}"
      create_home: yes 
      home: "{{ user.home }}"
      shell: "{{ user.shell }}"
      skeleton: /etc/skel
      state: present

- name: Install the latest version of pip
  yum:
    name:
      - epel-release
      - git
      - python-pip
    state: latest
  become: yes
  become_user: root

- name: Clone the code repository to the user home dir.
  git:
    repo: "https://github.com/rgajfullin/fix_test.git"
    dest: "{{ user.home }}/monitoring_bot"
    force: True
  become: yes
  become_user: "{{ user.name }}"

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip
  become: yes
  become_user: root

- name: create virtualenv and install requirements
  pip: 
     requirements: "{{ user.home }}/monitoring_bot/bot/requirements.txt" 
     virtualenv: "{{ user.home }}/monitoring_bot/venv/"

- name: Add bot config
  template: src=bot_config.j2 dest="{{ user.home }}/monitoring_bot/bot/config.json" owner={{ user.name }} group={{ user.name }}
  notify:
    - Restart telegram monitoring bot

- name: Add systemd config
  template: src=telegram_bot_systemd.j2 dest=/etc/systemd/system/telegram-monitoring-bot.service 
  notify:
    - Restart telegram monitoring bot 

